services:
  db:
    image: postgres:16.2
    restart: always
    container_name: bytesizedb
    volumes:
      - db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DATABSE: gorm_test
volumes:
  db: